version: '3'

services:
  agritech-mqtt:
    image: eclipse-mosquitto
    container_name: agritech-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - ./data/mosquitto:/mosquitto/data
    networks:
      - agritech-network
      
  agritech-db:
    build:
      context: ./config/db
      dockerfile: Dockerfile
    container_name: agritech-db
    restart: always
    environment:
      MYSQL_DATABASE: 'agritech_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - agritech-network
      
  agritech-server:
    build:
      context: ./src/server
    container_name: agritech-server
    ports:
      - "8080:8080"
    networks:
      - agritech-network
    depends_on:
      - agritech-mqtt
      - agritech-db


networks:
  agritech-network:
    driver: bridge

volumes:
  my-db:

