version: '3'

services:
  agritech-mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - ./data/mosquitto:/mosquitto/data
    networks:
      - agritech_network
      
  agritech-db:
    build:
      context: ./config/db
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'agritech_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
      - ./data/db:/var/lib/mysql
    networks:
      - agritech_network
      
  go_server:
    build:
      context: ./src/server
    ports:
      - "8080:8080"
    networks:
      - agritech_network
    depends_on:
      - agritech-mosquitto
      - agritech-db


networks:
  agritech_network:
    driver: bridge

volumes:
  my-db:

